### ISSUE TITLE
Question: Does it only work client side

### ISSUE THREAD

**Issue by shreypjain** [justinmahar/openai-ext#1]
Hey Justin – wanted to ask if this project is only supposed to be used client side. Then that would answer me testing is server side, and it telling me this:

`ReferenceError: XMLHttpRequest is not defined`

**Comment by justinmahar** [comment]
Hey! Yes this currently only works on the client. Might add support for server-side streaming next week, need to put more time into it when I’m able to

In the mean time, the stream discussion has a lot of server-side attempts that seem to work for people. I’d give those a shot.

If you find one that works, you can post it here and I’ll do my best to bake it into this library for everyone

**Comment by shreypjain** [comment]
That makes sense – and yes I had an axios version working server side so no worries there. 

So quick question for you, why do I get the isFinal flag give me true twice? It also seems like any time I call `streamChatCompletions` it makes two network requests?

![image](https://user-images.githubusercontent.com/47904393/232332373-0fdfc9df-8239-4572-b40c-cf66fa0f9741.png)

Here is the piece of code that is relevant for it:
```
const streamHandler: StreamChatCompletionHandler = {
    onContent(content, isFinal, xhr) {
      if (!isFinal) {
        setLatestMessage(content);
      } 
      if (isFinal) {
        console.log("here")
        setIsGenerating(true);
        laggingMessages.push({
          role: "assistant",
          content: content,
        });
        setMessages(laggingMessages);
        setLatestMessage("");
        laggingLatestMessage = "";
      }
    },
    onDone(xhr) {},
    onError(error, status, xhr) {
      console.error(error);
      setLatestMessage(
        "I'm sorry, there was an unexpected error on our end. Please refresh the page and try again"
      );
    },
  };

  const sendChatQuery = async (content: string) => {
    setInputValue("");
    laggingMessages.push({
      role: "user",
      content,
    });
    setMessages(
      [
        ...messages,
        {
          role: "user",
          content,
        },
      ],
      async (_, newMessages) => {
        setIsGenerating(true);
        await OpenAIExt.streamChatCompletion(
          {
            model: "gpt-3.5-turbo",
            messages: newMessages,
          },
          streamConfig,
          streamHandler
        );
      }
    );
  };
```
Is that the design of the library? @justinmahar

**Comment by shreypjain** [comment]
Yep it looks like it's making two requests, since onDone is being called twice. I want isFinal or onDone to be called once though, or some way to know the content is done generating for sure and not give me some duplicates. Let me know if that's possible?

Shrey

**Comment by shreypjain** [comment]
[UPDATE] – No longer having this issue, saw that I was actually having some rerender issues with my custom hook.

**Comment by justinmahar** [comment]
@shreypjain I've updated the library to support streaming on the server, too 👍 

Here's the quick start for how to use it: https://github.com/justinmahar/openai-ext#nodejs--server

Closing this issue for now
